// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NdRViagens.Data;

#nullable disable

namespace NdRViagens.Migrations
{
    [DbContext(typeof(NdRDbContext))]
    partial class NdRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NdRViagens.Models.Destino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cidade");

                    b.HasKey("Id");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("NdRViagens.Models.PacoteViagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<bool>("Alimentacao")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Alimentacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<long>("Destino_ID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Hospedagem")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Hospedagem");

                    b.Property<bool>("Ingressos")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ingressos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("Preco");

                    b.Property<decimal?>("PrecoPromo")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("Preco_Promo");

                    b.HasKey("Id");

                    b.HasIndex("Destino_ID");

                    b.ToTable("Pacotes");
                });

            modelBuilder.Entity("NdRViagens.Models.PacoteViagem", b =>
                {
                    b.HasOne("NdRViagens.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("Destino_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");
                });
#pragma warning restore 612, 618
        }
    }
}
